# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-31 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20170818_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='color',
            field=models.CharField(blank=True, default='#FFF', max_length=20, null=True),
        ),
    ]
