# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-05 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20170831_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='facebook',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='linkedin',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.TextField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='twitter',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='url',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
