# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-01 20:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmanagement',
            name='created',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2017, 8, 1, 20, 43, 56, 663000, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
