# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-03 17:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_accounting_company'),
        ('user', '0002_clientmanagement_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='clients',
        ),
        migrations.AddField(
            model_name='invite',
            name='invited_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.Company'),
            preserve_default=False,
        ),
    ]
