# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-09 21:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def create_global_apps(app, schema_editor):
    from apps.models import App as app_cls

    print "Creating global apps"
    app_cls.objects.create(
        name="QuickBooks",
        category="Accounting",
        url="https://qbo.intuit.com/qbo1/login",
        logo="quickbooks.png"
    )

    app_cls.objects.create(
        name="Xero",
        category="Accounting",
        url="https://login.xero.com/",
        logo="xero.png"
    )

    app_cls.objects.create(
        name="Bill.com",
        category="A/P and A/R",
        url="https://app.bill.com/Login",
        logo="bill.com.png"
    )

    app_cls.objects.create(
        name="Hubdoc",
        category="Document Retrieval",
        url="https://app.hubdoc.com/login",
        logo="hubdoc.png"
    )

    app_cls.objects.create(
        name="ReceiptBank",
        category="Receipt Capture",
        url="https://app.receipt-bank.com/login",
        logo="receipt-bank.png"
    )

    app_cls.objects.create(
        name="Gusto",
        category="Payroll",
        url="https://app.gusto.com/login",
        logo="gusto.png"
    )

    app_cls.objects.create(
        name="Expensify",
        category="Expense Management",
        url="https://www.expensify.com/signin",
        logo="expensify.png"
    )

    app_cls.objects.create(
        name="Tallie",
        category="Expense Management",
        url="https://usetallie.com/sso/Account/LogOn",
        logo="tallie.png"
    )

    app_cls.objects.create(
        name="TSheets",
        category="Time Tracking",
        url="https://www.tsheets.com/signin",
        logo="tsheets.png"
    )

    app_cls.objects.create(
        name="Mile IQ",
        category="Mileage Tracking",
        url="https://dashboard.mileiq.com/login/auth",
        logo="mileiq.png"
    )




class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('category', models.TextField(blank=True, max_length=250, null=True)),
                ('url', models.CharField(blank=True, max_length=250, null=True)),
                ('logo', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserHasApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.App')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(create_global_apps),
    ]
