# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-22 15:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_app_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyhasapp',
            options={'ordering': ['order']},
        ),
    ]
