# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-31 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    def create_global_resources(app, schema_editor):
        from resources.models import Resource as resource_cls

        print "Creating global resources"
        resource_cls.objects.create(
            name="Reconcile Accounts",
            category="QuickBooks Online",
            file_type=3,
            description="Tutorial video from Intuit QuickBooks",
            url="https://quickbooks.intuit.com/tutorials/lessons/reconcile-accounts/",
        )

        resource_cls.objects.create(
            name="Online Banking Overview",
            category="QuickBooks Online",
            file_type=3,
            description="Tutorial video from Intuit QuickBooks",
            url="https://quickbooks.intuit.com/tutorials/lessons/connect-to-bank-account/",
        )

        resource_cls.objects.create(
            name="Managing Expenses in QuickBooks",
            category="QuickBooks Online",
            file_type=3,
            description="Tutorial video from Intuit QuickBooks",
            url="https://quickbooks.intuit.com/tutorials/lessons/manage-expenses-in-quickbooks/",
        )

        resource_cls.objects.create(
            name="Using Bank Rules ",
            category="QuickBooks Online",
            file_type=3,
            description="Tutorial video from Intuit QuickBooks",
            url="https://quickbooks.intuit.com/tutorials/lessons/qboa-bank-rules/",
        )

        resource_cls.objects.create(
            name="Receive Payments in QuickBooks",
            category="QuickBooks Online",
            file_type=3,
            description="Tutorial video from Intuit QuickBooks",
            url="https://quickbooks.intuit.com/tutorials/lessons/receive-customer-payments/",
        )

        resource_cls.objects.create(
            name="How to Set up and Use QuickBooks Payments",
            category="QuickBooks Online",
            file_type=3,
            description="Tutorial video from Intuit QuickBooks",
            url="https://quickbooks.intuit.com/tutorials/lessons/how-to-set-up-and-use-quickbooks-payments/",
        )

        resource_cls.objects.create(
            name="Managing Sales and Income ",
            category="QuickBooks Online",
            file_type=3,
            description="Tutorial video from Intuit QuickBooks",
            url="http://quickbooks.intuit.com/tutorials/lessons/sales-related-tasks/",
        )

        resource_cls.objects.create(
            name="Add Products",
            category="QuickBooks Online",
            file_type=3,
            description="Tutorial video from Intuit QuickBooks",
            url="https://quickbooks.intuit.com/tutorials/lessons/add-products-information/",
        )

        resource_cls.objects.create(
            name="Save and Schedule Customized Reports",
            category="QuickBooks Online",
            file_type=3,
            description="Tutorial video from Intuit QuickBooks",
            url="https://quickbooks.intuit.com/tutorials/lessons/save-and-schedule-customized-reports/",
        )

        resource_cls.objects.create(
            name="Bank Reconciliation in Xero",
            category="Xero",
            file_type=3,
            description="How To video from Xero TV",
            url="https://tv.xero.com/detail/videos/banking/video/5130954875001/bank-reconciliation-in-xero?autoStart=true",
        )

        resource_cls.objects.create(
            name="Bank Reconciliation in Xero",
            category="Xero",
            file_type=3,
            description="How To video from Xero TV",
            url="https://tv.xero.com/detail/videos/banking/video/5130954875001/bank-reconciliation-in-xero?autoStart=true",
        )

        resource_cls.objects.create(
            name="Use Bank Rules to Automate Reconciliation in Xero",
            category="Xero",
            file_type=3,
            description="How To video from Xero TV",
            url="https://tv.xero.com/detail/videos/banking/video/5127808505001/using-bank-rules-to-automate-reconciliation-in-xero?autoStart=true",
        )

        resource_cls.objects.create(
            name="Sales and Online Invoicing in Xero",
            category="Xero",
            file_type=3,
            description="How To video from Xero TV",
            url="https://tv.xero.com/detail/videos/sales/video/5131005465001/sales-and-online-invoicing-in-xero?autoStart=true",
        )

        resource_cls.objects.create(
            name="Managing Bills and Purchases in Xero",
            category="Xero",
            file_type=3,
            description="How To video from Xero TV",
            url="https://tv.xero.com/detail/videos/purchases/video/5130942894001/manage-bills-and-purchases-in-xero?autoStart=true",
        )

        resource_cls.objects.create(
            name="BIllable expense in Xero",
            category="Xero",
            file_type=3,
            description="How To video from Xero TV",
            url="https://tv.xero.com/detail/videos/purchases/video/5130942887001/billable-expenses-in-xero?autoStart=true",
        )

        resource_cls.objects.create(
            name="Prepayments in Xero",
            category="Xero",
            file_type=3,
            description="How To video from Xero TV",
            url="https://tv.xero.com/detail/videos/purchases/video/5127833259001/prepayments-in-xero?autoStart=true",
        )

        resource_cls.objects.create(
            name="Overpayments in Xero",
            category="Xero",
            file_type=3,
            description="How To video from Xero TV",
            url="https://tv.xero.com/detail/videos/purchases/video/5127826535001/overpayments-in-xero?autoStart=true",
        )

        resource_cls.objects.create(
            name="Tracking Inventory Made Simple in Xero",
            category="Xero",
            file_type=3,
            description="How To video from Xero TV",
            url="https://tv.xero.com/detail/videos/inventory/video/5127833297001/tracking-inventory-made-simple-with-xero?autoStart=true",
        )

        resource_cls.objects.create(
            name="Getting Started with ReceiptBank",
            category="ReceiptBank",
            file_type=3,
            description="A full walkthrough guide to setting up your Receipt Bank account",
            url="https://www.youtube.com/watch?v=q-beaYgyMoA",
        )

        resource_cls.objects.create(
            name="Hubdoc Onboarding - Client Perspective",
            category="Hubdoc",
            file_type=3,
            description="So, your accountant or bookkeeper signed you up for HubDoc -- now what?",
            url="https://www.youtube.com/watch?v=B__82up_JHU&t=3s",
        )

        resource_cls.objects.create(
            name="Accounts Payable in Bill.com",
            category="Bill.com",
            file_type=3,
            description="The demo highlights the features and benefits of Bill.com Accounts Payable.",
            url="https://vimeo.com/190790858",
        )

        resource_cls.objects.create(
            name="Accounts Receivable in Bill.com",
            category="Bill.com",
            file_type=3,
            description="The demo highlights the features and benefits of Bill.com Accounts Receivable.",
            url="https://vimeo.com/166368105",
        )

        resource_cls.objects.create(
            name="Run Payroll in Gusto",
            category="Gusto",
            file_type=3,
            description="Demo to run payroll in 60 seconds with Gusto",
            url="https://www.youtube.com/watch?v=mKzCshL-fqw",
        )

        resource_cls.objects.create(
            name="Employee Training on TSheets Desktop",
            category="TSheets",
            file_type=3,
            description="Learn the ins and outs of the TSheets web dashboard! This training is specific to employees.",
            url="https://www.youtube.com/watch?v=BiXZX1jBCV4",
        )

        resource_cls.objects.create(
            name="Employee Training on TSheets Mobile App",
            category="TSheets",
            file_type=3,
            description="Learn the ins and outs of the TSheets mobile app! This training is specific to employees.",
            url="https://www.youtube.com/watch?v=pz9-Yrnjj_Y",
        )

        resource_cls.objects.create(
            name="Tallie Expense Reports: End User Webinar",
            category="Tallie",
            file_type=3,
            description="A short webinar geared towards users just getting starting with Tallie.",
            url="https://www.youtube.com/watch?v=ABGDH0CllcI",
        )

        resource_cls.objects.create(
            name="Tallie End User Training: Mobile App",
            category="Tallie",
            file_type=3,
            description="Learn how to code your expenses, upload your receipt images, track mileage, and format your expense reports - all from your app!!!",
            url="https://www.youtube.com/watch?v=qEMmmYyUQRo",
        )

        resource_cls.objects.create(
            name="Expensify Workshop: Training for Employees and Individuals",
            category="Expensify",
            file_type=3,
            description="This recorded workshop is intended to help employees and individuals who would like to understand more about Expensify's workflow and basic functionality.",
            url="https://www.youtube.com/watch?v=E0dhGkFagG0",
        )

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='category',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='file_type',
            field=models.IntegerField(choices=[(1, 'Document'), (2, 'Spreadsheet'), (3, 'Video'), (4, 'Image')], default=1, null=True),
        ),
        migrations.RunPython(create_global_resources),
    ]
